#!/bin/sh

# Some colors for the output
GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Clean up the dist folder
rm -rf dist/keystone-adventure

# Check if production or staging
production=false
while getopts 'p' opt; do
  production=true
done
shift "$(($OPTIND -1))"

# Set the configuration variable
configuration="staging"
if [[ "$production" = true ]]
then
  configuration="production"
fi

# Generate the matching bundle
echo "\n${RED}»»» WATCH OUT THIS SCRIPT WILL PUBLISH TO A SPECIAL FOLDER!!! «««${NC}\n"
echo "${GREEN}»»» Generating $configuration bundle «««${NC}"
ng build --configuration $configuration

# Clean up the remote playground folder
remote="climbdal@keystone-adventures.com"
echo "\n${GREEN}»»» Cleaning remote directories «««${NC}\n"
echo "    » Local system name: $HOSTNAME"
echo "    » Local date and time: $(date)"

if [[ "$production" = true ]]
then
  folder="public_html/dehong"
  echo "\n${GREEN}»»» Running commands on remote host named $remote folder 'public_html/${RED}dehong${GREEN}' «««${NC}\n"
  ssh -T $remote <<'EOL'
	now="$(date)"
	name="$HOSTNAME"
	up="$(uptime)"
	echo "    » Server name is $name"
	echo "    » Server date and time is $now"
	echo "    » Server uptime: $up"
	cd public_html/dehong
	rm *.js manifest.* ngsw.json *.css index.html favicon.ico
  [ ! -e *.map ] || rm *.map
  rm -rf assets/
	echo "Bye"
EOL
  # Publish the to production subfolder
  echo "\n${GREEN}»»» Publishing $configuration bundle to $remote:${RED}$folder${NC} «««${NC}\n"
  rsync -azvh dist/keystone-registration/ $remote:$folder
fi
# Publish to the registration folder both in production and staging
echo "\n${GREEN}»»» Running commands on remote host named $remote folder 'public_html/registration' «««${NC}\n"
ssh -T $remote <<'EOL'
now="$(date)"
name="$HOSTNAME"
up="$(uptime)"
echo "    » Server name is $name"
echo "    » Server date and time is $now"
echo "    » Server uptime: $up"
cd public_html/registration
rm *.js manifest.* ngsw.json *.css index.html favicon.ico
[ ! -e *.map ] || rm *.map
rm -rf assets/
echo "Bye"
EOL

# Publish to the staging subfolder
folder="public_html/registration"
target="$remote:$folder"
echo "\n${GREEN}»»» Publishing $configuration bundle to $target «««${NC}\n"
rsync -azvh dist/keystone-registration/ $target
