// Convert this autogenerated test to use the functional guard.
// https://www.danywalls.com/testing-functional-guards-in-angular-15-a-step-by-step-guide

// describe('PendingChangesGuard', () => {
// let guard: PendingChangesGuard;
// beforeEach(() => {
//   TestBed.configureTestingModule({});
//   guard = TestBed.inject(PendingChangesGuard);
// });
// it('should be created', () => {
//   expect(guard).toBeTruthy();
// });
// });
